#      volumes:
#        - my_docker_volume:/volume_mount
name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20-bookworm
      env:
        NODE_ENV: development
      ports:
        - 80
    steps:
      - uses: actions/checkout@v4
      - run: rm -rf node_modules fe-web/node_modules dist fe-web/dist
      - run: cd fe-web && npm i
      - run: cd fe-web && npm run build
